# Generated by Django 4.2.7 on 2024-04-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
