# Generated by Django 4.2.7 on 2024-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0002_roomcategory_alter_booking_room_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
