# Generated by Django 4.2.7 on 2023-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0002_facility_room_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
                ('is_booked', models.BooleanField(default=True)),
            ],
        ),
    ]
