# Generated by Django 4.2.7 on 2024-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0003_userregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='image',
            field=models.ImageField(default=1, upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
