# Generated by Django 4.2.7 on 2024-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0004_userregistration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='image',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/1459071_576423112429002_1714649276_n.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
