# Generated by Django 4.2.7 on 2024-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0005_remove_userregistration_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/1459071_576423112429002_1714649276_n.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
