# Generated by Django 4.2.7 on 2024-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0006_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Payment History', 'verbose_name_plural': 'Payment History'},
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='total_bookings_rewards',
            field=models.IntegerField(default=0),
        ),
    ]
