# Generated by Django 4.2.7 on 2024-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0006_alter_userregistration_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='category_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/defaultimage.png', null=True, upload_to='profile_images/'),
        ),
    ]
