# Generated by Django 4.2.7 on 2024-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0007_roomcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
