# Generated by Django 4.2.7 on 2024-02-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0008_roomcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='rooms_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
