# Generated by Django 4.2.7 on 2024-02-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0010_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
