# Generated by Django 4.2.7 on 2024-03-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0011_alter_room_name_alter_roomcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(related_name='Facility', to='BookingEngineApp.facility'),
        ),
    ]
