# Generated by Django 4.2.7 on 2024-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0012_alter_notification_id_alter_notification_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
