# Generated by Django 4.2.7 on 2024-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0012_alter_facility_name_alter_room_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(related_name='facility', to='BookingEngineApp.facility'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(default='profile_images/defaultimage.png', upload_to='category_images/'),
        ),
    ]
