# Generated by Django 4.2.7 on 2024-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0013_alter_room_facility_alter_roomcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(to='BookingEngineApp.facility'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(upload_to='category_images/'),
        ),
    ]
