# Generated by Django 4.2.7 on 2024-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0013_remove_notification_username_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
