# Generated by Django 4.2.7 on 2024-03-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0014_alter_room_facility_alter_roomcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
