# Generated by Django 4.2.7 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0015_remove_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
