# Generated by Django 4.2.7 on 2024-04-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0016_notification_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
    ]
