# Generated by Django 4.2.7 on 2024-04-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0017_remove_notification_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
