# Generated by Django 4.2.7 on 2024-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0018_alter_room_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(related_name='rooms', to='BookingEngineApp.facility'),
        ),
    ]
