# Generated by Django 4.2.7 on 2024-03-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0019_alter_room_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='credits_received',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='credits_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='credits_received',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='credits_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
