# Generated by Django 4.2.7 on 2024-03-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0021_rename_room_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='room',
        ),
    ]
