# Generated by Django 4.2.7 on 2024-03-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0022_rename_name_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
    ]
