# Generated by Django 4.2.7 on 2024-03-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0023_remove_booking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='name',
        ),
    ]
