# Generated by Django 4.2.7 on 2024-03-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0024_rename_room_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
