# Generated by Django 4.2.7 on 2024-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0025_remove_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
