# Generated by Django 4.2.7 on 2024-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0026_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grand_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_credits_received',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_credits_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
