# Generated by Django 4.2.7 on 2024-03-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0027_booking_grand_total_booking_total_credits_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_credits_received',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_credits_required',
        ),
    ]
