# Generated by Django 4.2.7 on 2024-03-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0028_remove_booking_total_credits_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sleeps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
