# Generated by Django 4.2.7 on 2024-03-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0029_room_sleeps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='credits_received',
        ),
        migrations.RemoveField(
            model_name='room',
            name='credits_required',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sleeps',
        ),
    ]
