# Generated by Django 4.2.7 on 2024-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0031_room_credits_received_room_credits_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
