# Generated by Django 4.2.7 on 2024-03-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0032_booking_adult_booking_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occupancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
