# Generated by Django 4.2.7 on 2024-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0033_booking_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_credits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_rewards',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
