# Generated by Django 4.2.7 on 2024-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0034_booking_booking_credits_booking_booking_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='role',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='total_bookings_rewards',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
