# Generated by Django 4.2.7 on 2024-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0035_remove_userregistration_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
