# Generated by Django 4.2.7 on 2024-03-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingEngineApp', '0036_booking_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='duration',
            new_name='stay_duration',
        ),
    ]
